### ISSUE TITLE
Django possibly sharing transkribus sessions

### ISSUE THREAD

**Issue by cziaarm** [Transkribus/TWI-mc#1]
![ss1](https://cloud.githubusercontent.com/assets/1931982/25998654/f6d667aa-3719-11e7-85cf-9d405e05b29b.png)

Returning to an open browser I appear to be logged in as @hackmanschorsch (!)

Possible cause: django keeps my session open, my transkribus session expires. Schorsh logs in and gets transkribus session with the same reference (django/transkribus?). My django session can now talk to transkrinus with schorsch's session.

**Comment by cziaarm** [comment]
Adding userid to t_gen_request_id (which is used to identify cached transkribus data)

**Comment by cziaarm** [comment]
@hackmanschorsch @kansallisarkisto Please go to https://transkribus.eu/readTest/library/ and check that you are getting the correct data for the user you are logged in as.

**Comment by hackmanschorsch** [comment]
My observation was this: I logged in wtih two different accounts - see several collections with the first and just one with the other. Reloading the first application lets me see the collection from my second account??

________________________________
Von: Rory McNicholl [notifications@github.com]
Gesendet: Mittwoch, 17. Mai 2017 14:45
An: Transkribus/TWI-mc
Cc: Hackl, Günter; Mention
Betreff: Re: [Transkribus/TWI-mc] Django possibly sharing transkribus sessions (#1)


@hackmanschorsch<https://github.com/hackmanschorsch> @kansallisarkisto<https://github.com/kansallisarkisto> Please go to https://transkribus.eu/readTest/library/ and check that you are getting the correct data for the user you are logged in as.

**Comment by cziaarm** [comment]
@hackmanschorsch confirmed

**Comment by cziaarm** [comment]
A better candidate solution in place 83c612f

Transkribus session is stored against user object

also methods in utils/services.py are now in class  TranskribusSession

**Comment by cziaarm** [comment]
<script src="https://gist.github.com/cziaarm/ca91f6489bd5a7adb2e9eed99b0e2c14.js"></script>

**Comment by cziaarm** [comment]
`<script src="https://gist.github.com/cziaarm/ca91f6489bd5a7adb2e9eed99b0e2c14.js"></script>`
