### ISSUE TITLE
Link directly to login instead of error message

### ISSUE THREAD

**Issue by hackmanschorsch** [Transkribus/TWI-mc#10]
Instead of showing
'We have a slight problem: Transkribus session is unauthorised, you must (re)log on to Transkribus-web. '
it would be much nicer to go directly to the login page in that case (and see the message there?). But may there is a good reason for this?

**Comment by cziaarm** [comment]
Agreed. That error_view view is a generic one with actions defined in a "switch" (well a python equivalent). I'll change the behaviour of the Unauth case so it redirects rather than displays the link.

**Comment by cziaarm** [comment]
Transkribus/TWI-utils/pull/7
