### ISSUE TITLE
Browse table should include status of pages, filtering and % of how much is done

### ISSUE THREAD

**Issue by jupouta** [Transkribus/TWI-mc#17]
**Browse** table should include
- the **number of pages (sum)** in each collection
- the number of docs
- filtering possibilities according to the **Role** (this way the user can see e.g. the collections that the user is owner of)
- **% figure** of how much of the collection has been transcribed by now.

**Comment by hackmanschorsch** [comment]
Last point needs to be formalized first and will be postponed therefor

**Comment by hackmanschorsch** [comment]
Number of pages: Should be enough to see on the collection level
Number of docs: is implemented
Filter for role: Already possible via Search box
% figure: e.g. we take the status 'Done' or 'Final' to indicate what is done

**Comment by hackmanschorsch** [comment]
The number of pages of a document/collection with an assigned status is now added to the collection and document metadata. Add param stats is true to get the statistical aggregated numbers for single collection:

https://transkribus.eu/TrpServer/rest/collections/2305/metadata?stats=true

aggregated metadata call for document:

https://transkribus.eu/TrpServer/rest/collections/2305/26455/fulldoc

@maxbry So we can show these numbers to the user. It's too expensive to load it for each collection or document automatically. Instead we have to load it via an extra ajax call for each entry.
@cziaarm And we can compute the % figure of how many pages are 'Final' from now on. But as we discussed in Helsinki this makes only sense for crowd projects at the moment.

**Comment by cziaarm** [comment]
@maxbry and @cziaarm to review the iinterface with the REST surface specifcally for the stats

**Comment by cziaarm** [comment]
@hackmanschorsch The collections/[id]/metadata is forbidden for crowdTranscribers

**Comment by cziaarm** [comment]
Candidate solution in place for  collections

**Comment by hackmanschorsch** [comment]
@cziaarm Which collection did you test this - you are currently only added as crowdTranscriber in collection 6903 in the database? At least there it should work.

**Comment by cziaarm** [comment]
Ah @hackmanschorsch that's odd. You are correct in that my user can access the rest service (https://transkribus.eu/TrpServer/rest/collections/6903/metadata?stats=true), but when the webUI sends a request... it is met with a 403... Let me look into it  further...

**Comment by cziaarm** [comment]
@hackmanschorsch OK There is a 403, but not from metadata... it's from the actions call to get the recent save

https://transkribus.eu/TrpServer/rest/actions/list?collId=6903&typeid=1&nValues=1&userid=65

Gives me a 403 (I am a crowdTranscriber for this collection)
