### ISSUE TITLE
Searching for words with Scandinavian letters with umlaut (ä/ö/ü/å) shows a picture as result

### ISSUE THREAD

**Issue by jupouta** [Transkribus/TWI-mc#20]
Browse --> **Search: words with umlaut**

When searching a word that includes umlaut or some sort of dots (ä/ö/ü/å/ë), the results show a picture of a document (apparently the first document) but nothing else.

**Comment by hackmanschorsch** [comment]
@jupouta Is that a search e.g. in the collections table? Tried this with ä and ö and got correct results.
