### ISSUE TITLE
Edit line: the line that's edited should turn into green

### ISSUE THREAD

**Issue by jupouta** [Transkribus/TWI-mc#25]
Edit interface --> **Edit line**

The chosen line is green, but if I decide to edit the line before that, the line that's **being edited at that moment** should turn into green.

Also the **circle** should turn into green as well.

**Comment by kansallisarkisto** [comment]
Is this the behaviour we want now? At the moment the line in the middle is always green and the circle corresponding to it is filled but any line shown in the dialog can indeed be edited. Should that behaviour change? Can we make a decision?
