### ISSUE TITLE
Edit line disappears OR stays big after zooming out

### ISSUE THREAD

**Issue by jupouta** [Transkribus/TWI-mc#28]
Edit interface --> Edit line

The Edit line box sometimes disappears completely and sometimes stays big after zooming out (**Firefox**). This doesn't happen every time though.

**Comment by EvaMLang** [comment]
Could not reproduce the error.

One thing that strikes me, though, is that after switching between image mode and line-by-line mode, I (as user) need to be aware that I need to click on a line first to see the box. 

Also, when switching to the next page, edit mode remains, on the second-to-next page, I am in viewing mode. Is this a bug or a feature?

**Comment by cziaarm** [comment]
@hackmanschorsch confirms this is now fixed
