### ISSUE TITLE
My Collections should show Showing X to Y of Y entries

### ISSUE THREAD

**Issue by jupouta** [Transkribus/TWI-mc#35]
Dashboard --> My Collections

The text _You are a member of the following X collections:_ should also show how many entries are **not** shown (_Showing X to Y of Y entries_).

Now the user might have have 20 collections of which 5 are shown on the list but it still says _You are a member of the **following** 20 collections:_.

**Comment by maxbry** [comment]
Under the table, there is a sentence saying in my case 'Showing 1 to 5 of 6 entries'. Is that what you mean or do you want to have the message shown more prominently?

**Comment by jupouta** [comment]
Yes, that's what I mean. It should appear upper, at the same line with 'You are a member of the following X collections' cause now it's a bit confusing.
