### ISSUE TITLE
WebUI test collection

### ISSUE THREAD

**Issue by hackmanschorsch** [Transkribus/TWI-mc#38]
@cziaarm Please share your test collection with us to have a common resource for developing and testing and where all of us can upload our documents. Cheers!

**Comment by cziaarm** [comment]
Eva
Günter
Julia
Louise
Maria
Matti
Max
Nathanael
Philip
Schorsch
Vili

All now owners of WebUITestCollection

**Comment by cziaarm** [comment]
Hi Schorsch, fancy giving this collection the once over... make sureI haven't mucked anything up. Cheers

**Comment by hackmanschorsch** [comment]
Added some first demo documents. All are duplicated - so you are free to play around when testing and deploying. And please add documents of your own too or tell me the DocID so that I can do it.

**Comment by EvaMLang** [comment]
Added GT ABP documents as play set (duplicated). Note, all of them should have status "GT" - no HTR process was run on them.
