### ISSUE TITLE
The "document" page

### ISSUE THREAD

**Issue by cziaarm** [Transkribus/TWI-mc#44]
Currently The edit page (eg https://transkribus.eu/readTest/edit/correct/2305/23316/1) gives us a selection of editing interfaes and the means to browse through a the pages in a document using the thumbnail ribbon.

Allowing essentially this page but with the editing possibilities turned off would provide a usefule "document" page to give users a read-only view of the document with zooming and thumbnail ribbon etc

Editing options could be enabled using a button where possible. Toggling the editing option could also be protected by user/collection permissions, which would allow us to use the same view for the "published collections" in the future.

**Comment by jnphilipp** [comment]
This also would need to be coordinated with [#6](https://github.com/Transkribus/TWI-mc/issues/6).

**Comment by cziaarm** [comment]
Just checking in on this one...

To enumerate the tasks I think are required to get a candidate ready:

- view only mode
- page nav (we already have the ribbon, I can get the arrows working too maybe?)
- Add some document metadata to top of page

I can look into making the arrow navs work and maybe the document metadata if you guys are ok with making the "view-only" mode happen??

Any assistance required to make it happen, just let me know, was looking to reach milestone v1.01 today :)

**Comment by cziaarm** [comment]
hmm this is kind of a duplicate of Transkribus/TWI-edit#17

**Comment by cziaarm** [comment]
commit https://github.com/Transkribus/TWI-edit/commit/a425038cd61592855bcf6bb92eb3d9fb1af68e97 sorts nav from doc to doc by arrows

**Comment by cziaarm** [comment]
https://github.com/Transkribus/TWI-edit/commit/0c376a1a882338d942a19f268a551a186dd3b56a puts in a modal that will display document metadata

TODO : define a subset of metadata that should be displayed in the modal and do so prettily.
