### ISSUE TITLE
JS alert on "My collections page"

### ISSUE THREAD

**Issue by cziaarm** [Transkribus/TWI-mc#45]
Occasionally in https://transkribus.eu/readTest/library/

Problem with getting nrOfDocument data

results in error alert:

"DataTables warning: table id=collections_table - Requested unknown parameter 'nrOfDocuments' for row 0, column 4. For more information about this error, please see http://datatables.net/tn/4"

Possibly a good reason for error and we need to handle better?

**Comment by cziaarm** [comment]
@hackmanschorsch Have stopped the warnings, because nrOfDocuments is no longer in the data that is being returned to the table. A question remains about whther and how the nrOfDocuments is displayed

@EvaMLang please confirm that the warnings have stopped interrupting the page loading. And close #46 too if successful

**Comment by EvaMLang** [comment]
Rory, I can confirm that warnings stopped.
