### ISSUE TITLE
Translations

### ISSUE THREAD

**Issue by jnphilipp** [Transkribus/TWI-mc#51]
* [German translation](https://github.com/Transkribus/TWI-mc/blob/master/mc/locale/de/LC_MESSAGES/django.po)

* [Finnish translation](https://github.com/Transkribus/TWI-mc/blob/master/mc/locale/fi/LC_MESSAGES/django.po)

**Comment by cziaarm** [comment]
Requires a phrase freeze and final run on these

**Comment by cziaarm** [comment]
@EvaMLang ( @kansallisarkisto or whoever is doing the Finnish one)

Latest messages have been compiled so please review the links above...

We also have <a href="https://github.com/Transkribus/TWI-mc/blob/master/mc/locale/sv/LC_MESSAGES/django.po">Swedish</a> (I'm guessing that is you @kansallisarkisto ?)

An I have made some .po files for <a href="https://github.com/Transkribus/TWI-mc/blob/master/mc/locale/el/LC_MESSAGES/django.po">Greek</a>

<a href="https://github.com/Transkribus/TWI-mc/blob/master/mc/locale/es/LC_MESSAGES/django.po">Spanish</a>

and

<a href="https://github.com/Transkribus/TWI-mc/blob/master/mc/locale/fr/LC_MESSAGES/django.po">French</a>

JIC

**Comment by EvaMLang** [comment]
Update: German version done see latest commit https://github.com/Transkribus/TWI-mc/compare/issue_51_internationalization

**Comment by EvaMLang** [comment]
Update from user's call on 2018-02-02: 
Decision was to not use translations for the time-being. Once the system is going to stable release, we will re-introduce multi-language. 

@cziaarm @jnphilipp would you mind taking out anything but the English version for the next roudn of deployment until we are stable? Thank you!
