### ISSUE TITLE
Feature for channeling users to custom location upon successful registration

### ISSUE THREAD

**Issue by bejohu** [Transkribus/TWI-mc#54]
Facility to integrate registration with other websites, possibly limited to those under the same domain or a list of allowed origins.

For instance, X.example.com is where TWI-mc is running. This feature should enable a website on Y.example.com to channel visitors to X.example.com for creating an account. Upon successful account creation, the visitor, now as a logged-in user, is steered back to Y.example.com. Access to Transkribus server API should be possible at this point.

Channeling users from Y to X could be achieved by providing a "Sign Up" link refering the registration page on X. Channeling users back to Y could be providing them with a link refering to Y which is shown upon successful sign up.

Currently, there are no preferences as to implementation details such as use cookies, url params, etc.

**Comment by cziaarm** [comment]
This may be a little more specific than Berthold's original feature description, but...

 is there a way I can point the register link on the Web UI to the main transkribus.eu registration:

ie https://transkribus.eu/Transkribus/ (but with the reg modal open)

and then on successful registration be directed back to the read[Test]/library page?

question is for @hackmanschorsch and @kahlep

**Comment by hackmanschorsch** [comment]
But should we not wait with this until the new landing page is ready?

**Comment by cziaarm** [comment]
Register will link to static page explaining that you need to go and register at transkribus.eu and a link to that...

**Comment by bejohu** [comment]
How about this: 

1. User visits https://transkribus.eu#signupWebUI.

2. Homepage loads showing signup form.

3. Upon successful signup, user is redirected to pre-specified location, e.g. https://transkribus.eu/library/welcome.

4. Homepage adds parameter _trpSessionId_ to URL, e.g. https://transkribus.eu/library/welcome?trpSessionId=1234, so Web UI can authenticate user without requiring separate login.

This can easily be added to https://github.com/transkribus/TranskribusHomepage. WebUI can then use _/auth/refresh_ endpoint for verifying session ID.

**Comment by cziaarm** [comment]
To clarify, for now what needs to be tested is the link register link, the static page and the links from that. @behoju's comments are entirely valid, but not for this iteration.

**Comment by EvaMLang** [comment]
test failed: still to direct to the (old) login-mask under https://transkribus.eu/readTest/register 
![grafik](https://user-images.githubusercontent.com/17451573/32096863-ffc2abb8-bb07-11e7-8f91-d30960b289ea.png)
Note: test done on readTest in FF, Chrome throws a 500 upon trying to access go anywhere (either by giving direct URL or by using the browser history)

**Comment by EvaMLang** [comment]
Also: going from above screen to login (https://transkribus.eu/readTest/login/?next=/readTest/register) leads to 404 on https://transkribus.eu/readTest/register

**Comment by bejohu** [comment]
**Session sharing** has been implemented. It is intended to provide a solution for handling login / registration with minimal changes to existing infrastructure. Here is how it works:

First, not-yet-logged-in user navigates to _MyCollections_ home page. Provide [login](https://transkribus.eu/#loginWebUI) or [signup](https://transkribus.eu/#signupWebUI) to home page. User gets redirected to [home page](https://transkribus.eu). Signup / login dialog will open automatically.

Next, upon successful login a cookie _trpSessId_ is set containing session ID provided by transkribus API. Then user gets redirected back to _MyCollections_ to pre-specified URL depending on login or signup was performed.

Finally, _MyCollections_ provides view that validates cookie _trpSessId_ against transkribus API. If session is valid the user is authenticated. This is equivalent to logging in using valid credentials.

**Implementation.** The package [django-transkribus](https://github.com/bejohu/django-transkribus) provides a decorator for this. Configure as follows _urls.py_ to allow session sharing:

```python
...
from transkribus.decorators import session_sharing_allowed
...
urlpatterns = [
....
    url(r'^login/$', session_sharing_allowed(login_view, session_key='trpSessId'), name='login', kwargs={'template_name': 'app/login.html', 'redirect_authenticated_user': True, 'extra_context': {'next': '/'}}),
   ...
]
...
```

Alternatively, authentication can be done manually using _authenticate_with_cookie_ function.

```python
...
from django.contrib.auth import login
...
from transkribus.auth_backends import authenticate_with_cookie
...
if not request.user.is_authenticated():
    user = authenticate_with_cookie(request, session_key)
    if user is not None:
        login(request, user)
...
```

Please **note** that at the time of writing the version of the [home page](https://transkribus.eu) deployed does not yet incorporate the changes required to support session sharing.

**Comment by EvaMLang** [comment]
Not sure how to do user-side testing on this issue. 
The previously reported 404s are gone. 

@bejohu Please alert once single-sign-on / session sharing is fully incorporated and available for testing, thank you!
