### ISSUE TITLE
Make s-b-s and text read only

### ISSUE THREAD

**Issue by cziaarm** [Transkribus/TWI-mc#57]

**Comment by hackmanschorsch** [comment]
Seems not be deployed?

**Comment by cziaarm** [comment]
Dployment is up to date, I found this issue in the candidate solution column, which suggests that it had been committed to master (there were no pull requests either) @jnphilipp what is the status of this one?

**Comment by jnphilipp** [comment]
I had done this in https://github.com/Transkribus/TWI-edit/commit/fe1352ff24d2cdeec347f7410aad3b0117fe4565 and recommit it in https://github.com/Transkribus/TWI-edit/commit/536939231b79b9420fb812d75547f042a7337721. Since @kansallisarkisto did a bad merge.

**Comment by cziaarm** [comment]
Hi all, @jnphilipp can you help me understand which commit the TWI-edit module should be? At this stage we just want to tidy up the user experience (ie this ticket) shall I go all the way back to  Transkribus/TWI-edit@fe1352f ? or maybe Transkribus/TWI-edit@981a239 I think that would be preferable to breaking lots of stuff in pursuit of the more obscure caret related bugs.

**Comment by cziaarm** [comment]
OK I've gone ahead with Transkribus/TWI-edit@981a239  (given that people are expecting to test this thing)
