### ISSUE TITLE
Save changes does not save changes

### ISSUE THREAD

**Issue by GuenterMuehlberger** [Transkribus/TWI-mc#61]
Tags and transcripts are not saved.
https://transkribus.eu/readTest/edit/7927/26123/1

**Comment by hackmanschorsch** [comment]
save fails for me too saying 'You cannot change the status of this page'. Page status for this example is 'InProgress'. As said a while ago the logic of status handling should be done on the server side. At the moment there is no need for these limitations. So I would omit this check.

**Comment by hackmanschorsch** [comment]
And this behavior seems to be very new? So all in all we should think about to go back to the version we had a week ago?
